# Generated by Django 2.2.17 on 2021-02-12 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Memo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memo_title', models.CharField(max_length=200)),
                ('memo_type', models.CharField(max_length=200)),
                ('memo_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('delete', models.DateTimeField(blank=True, null=True, verbose_name='date deleted')),
            ],
        ),
    ]
